
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cs_aspnet_mvc_crud.Models
{

using System;
    using System.Collections.Generic;
    
public partial class contacto
{

    public int id { get; set; }

    public System.DateTime registration_date { get; set; }

    public string Phone { get; set; }

    public int user_id { get; set; }



    public virtual user user { get; set; }

}

}
